baseurl = "https://notes.gladstomych.com/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "blog"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  themeColor = "blue"
  ReadMore = "Read more"

[languages]
  [languages.en]
    title = "Gladstomych"
    subtitle = "Red Team | Security Research"
    keywords = "security, red team, offensive security, pentesting"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/gladstomych"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/blog"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "talks"
      name = "Talks"
      url = "/talks"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "tools"
      name = "Tools"
      url = "/tools"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 4
